version: "3.8"

services:
  rabbitmq_service:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork