version: "3.8"

services:
  db_line_provider:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - mynetwork

  line_provider:
    build:
      context: .
    env_file:
      - ./.env
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db_line_provider:
        condition: service_healthy
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
