"""init

Revision ID: 0a3cec8ea0d8
Revises: 
Create Date: 2024-08-12 23:29:32.082999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3cec8ea0d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'WIN_FIRST', 'WIN_SECOND', name='eventstate'), nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=32, scale=2), nullable=False),
    sa.CheckConstraint('coefficient > 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Numeric(precision=32, scale=2), nullable=False),
    sa.Column('amount_of_winnings', sa.Numeric(precision=32, scale=2), nullable=True),
    sa.Column('match_outcome', sa.Enum('WIN_FIRST', 'WIN_SECOND', name='matchoutcome'), nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=32, scale=2), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('bet_amount > 0'),
    sa.CheckConstraint('coefficient > 0'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    op.drop_table('event')
    # ### end Alembic commands ###
